#include <fat.h>
#include "booter.h"

int devicesInit() { // fatInitDefault seems required before device->startup() now
    if (!fatInitDefault()) { return -1; }
    fatUnmount("sd"); // clean up mount-points auto-generated by fatInitDefault
	fatUnmount("usb");
	return 0;
}

void deviceStop(device dev) {
	fatUnmount("fat");
	dev.interface->shutdown();
}

int deviceStart(device dev) {
	const DISC_INTERFACE* storage = dev.interface;
	if(!storage->startup()) { return -1; } // a mount must follow a startup
	if(!fatMountSimple("fat", storage)) { deviceStop(dev); return -2; }
	return 0;
}
